site_name:        AlphaVantage.jl
repo_url:         https://github.com/ellisvalentiner/AlphaVantage.jl
site_description: A Julia wrapper for the Alpha Vantage API.
site_author:      Ellis Valentiner

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
